//        project(
//            PROJ_DENIS,
//            "DENIS@Home",
//            "http://denis.usj.es/denisathome/",
//            "San Jorge University, Zaragoza, Spain",
//            tra("Medical physiology"),
//            tra("DENIS@Home does cardiac electrophysiological simulations, studying the electrical activity of the heart."),
//            "",
//            "",
//            "Study the physiology of the heart"
//        ),
//        project(
//            "FiND@Home",
//            "http://findah.ucd.ie/",
//            tra("University College Dublin"),
//            tra("Antimalarial drug discovery"),
//            tra("The parasite that causes malaria continues to evolve resistance to available medication. We therefore urgently need to discover new drugs, targeting new proteins in the parasite. The FiND@Home project is aimed at finding these new targets."),
//            "",
//            "",
//            "Develop malaria drugs"
//        ),
//        project(
//            "POEM@HOME",
//            "http://boinc.fzk.de/poem/",
//            tra("University of Karlsruhe (Germany)"),
//            tra("Protein structure prediction"),
//            tra("POEM@HOME uses a computational approach to predict the biologically active structure of proteins, to understand the signal-processing mechanisms when the proteins interact with one another, to understand diseases related to protein malfunction or aggregation, and to develop new drugs on the basis of the three-dimensions structure of biologically important proteins."),
//            "poem.jpg",
//            "",
//            "Study protein structure and interaction"
//        ),
//        project(
//            "Docking@Home",
//            "http://docking.cis.udel.edu/",
//            tra("University of Delaware"),
//            tra("Study of protein - ligand interactions"),
//            tra("Docking@Home has both bioscience and computer science goals. The project aims to further knowledge of the atomic details of protein-ligand interactions and, by doing so, will search for insights into the discovery of novel pharmaceuticals."),
//            "docking.png",
//            "",
//            "Study protein-ligand interactions"
//        ),
//        project(
//            "Simulation One",
//            "http://mmgboinc.unimi.it/",
//            "Universita degli Studi, Milan, Italy",
//            "Molecular biology",
//            "The project studies osmoprotectants - small molecules that protect proteins, for example by thermal stress. Thanks to these molecules in nature we can find plants able to survive without water, or bacteria able to survive in extreme environmental conditions. And how is this possible? Answering this question could have a major impact in agriculture, e.g. developing plants that require less water intake.",
//            "SimOne_logo.png",
//            "",
//            "Study molecules that protect proteins"
//        ),
//        project(
//            "Superlink@Technion",
//            "http://cbl-boinc-server2.cs.technion.ac.il/superlinkattechnion/",
//            tra("Technion, Israel"),
//            tra("Genetic linkage analysis"),
//            tra("Superlink@Technion helps geneticists all over the world find disease-provoking genes causing some types of diabetes, hypertension (high blood pressure), cancer, schizophrenia and many others."),
//            "superlink_logo.gif",
//            "",
//            "Find genetic causes of diseases"
//        ),
//        project(
//            "Proteins@Home",
//            "http://biology.polytechnique.fr/proteinsathome",
//            tra("Ecole Polytechnique, Paris"),
//            tra("Protein structure prediction"),
//            tra("By joining Proteins@Home, you will be part of a large-scale protein structure prediction project and help to advance an important area of science. By increasing our knowledge of proteins, you will contribute to a better understanding of many diseases and pathologies, and to progress in both medicine and technology. Proteins@Home is not for profit."),
//            "proteinsathome.gif"
//        ),
//        project(
//            "The Lattice Project",
//            "http://boinc.umiacs.umd.edu/",
//            tra("University of Maryland Center for Bioinformatics and Computational Biology"),
//            tra("Life science research"),
//            tra("The Lattice Project, developed and administered at the University of Maryland, supplies computing power to researchers worldwide who are studying evolutionary relationships using DNA and protein sequence data."),
//            "lattice.gif",
//            "",
//            "Study evolution using genetics"
//        ),
//        project(
//            "Malariacontrol.net",
//            "http://www.malariacontrol.net/",
//            tra("The Swiss Tropical Institute"),
//            tra("Epidemiology"),
//            tra("Simulation models of the transmission dynamics and health effects of malaria are an important tool for malaria control. They can be used to determine optimal strategies for delivering mosquito nets, chemotherapy, or new vaccines which are currently under development and testing.  Such modeling is extremely computer intensive, requiring simulations of large human populations with a diverse set of parameters related to biological and social factors that influence the distribution of the disease. "),
//            "africaathome.gif",
//            "",
//            "Study the spread of malaria"
//        ),
//        project(
//            "Tanpaku",
//            "http://issofty17.is.noda.tus.ac.jp/",
//            tra("Tokyo University of Science"),
//            tra("Biology"),
//            tra("To predict protein structure and function from genetic sequences, using the 'Brownian Dynamics' (BD) method.  This method enables us to simulate more efficiently than conventional methods."),
//            "tanpaku.jpg"
//        ),
//        project(
//            "Predictor@home",
//            "http://predictor.chem.lsa.umich.edu/",
//            tra("University of Michigan"),
//            tra("Biology"),
//            tra("Protein structure prediction starts from a sequence of amino acids and attempts to predict the folded, functioning, form of the protein.  Predicting the structure of an unknown protein is a critical problem in enabling structure-based drug design to treat new and existing diseases."),
//            "predictor.jpg"
//        ),
//        project(
//            "SIMAP",
//            "http://boincsimap.org/boincsimap/",
//            tra("University of Vienna"),
//            tra("Biology"),
//            tra("Calculate similarities between proteins. SIMAP provides a public database of the resulting data, which plays a key role in many bioinformatics research projects."),
//            "simaplogo.jpg",
//            "",
//            "Calculate similarities between proteins"
//        ),
//        project(
//            "Virtual Prairie",
//            "http://vcsc.cs.uh.edu/virtual-prairie/",
//            tra("University of Houston"),
//            tra("Study of botanical ecosystems"),
//            tra("Provide ecological guidelines on the design of prairies with the best potential for water purification.")
//        ),
//        project("XANSONS for COD",
//            "http://xansons4cod.com/xansons4cod/",
//            "Private; supported by the Russian Foundation for Basic Research.",
//            "Crystallography",
//            "XANSONS for COD is a research project aimed to create an open access database of simulated x-ray and neutron powder diffraction patterns for nanocrystalline phase of the materials presented in the Crystallography Open Database (COD).",
//            "",
//            "",
//            "Study nano-materials"
//        ),
//        project(
//            "CONVECTOR",
//            "http://convector.fsv.cvut.cz/",
//            "Czech Technical University in Prague",
//            tra("Mechanical engineering"),
//            tra("Currently we are calculating the optimum design of a structure call the 52 bar truss"),
//            "convector.jpg",
//            "",
//            "Study mechanical engineering"
//        ),
//        project(
//            "Constellation",
//            "http://aerospaceresearch.net/constellation/",
//            "<a href='http://rechenkraft.net'>Rechenkraft.net</a>, <a href='http://stuttgart.dglr.de'>DGLR</a>, <a href='http://selfnet.de'>Selfnet</a>, and <a href='http://shackspace.de'>shack</a>",
//            tra("Aerospace-related science and engineering"),
//            tra("Constellation is a platform for aerospace-related simulations, including trajectory optimization of launchers, satellites and probes, simulation of Moon's near-surface exosphere, and analysis of dynamic systems of exploration-rovers"),
//            "constellation2.png",
//            "",
//            tra("Perform aerospace-related simulations")
//        ),
//        project(
//            "eOn",
//            "http://eon.ices.utexas.edu/eon2/",
//            tra("University of Texas at Austin"),
//            tra("Chemistry"),
//            tra("A common problem in theoretical chemistry, condensed matter physics and materials science is the calculation of the time evolution of an atomic scale system where, for example, chemical reactions and/or diffusion occur. Generally the events of interest are quite rare (many orders of magnitude slower than the vibrational movements of the atoms), and therefore direct simulations, tracking every movement of the atoms, would take thousands of years of computer calculations on the fastest present day computer before a single event of interest can be expected to occur.  Our research group is interested in calculating the long time dynamics of systems."),
//            "",
//            "",
//            "Study the time evolution of atomic systems"
//        ),
//        project(
//            "Orbit@home",
//            "http://orbit.psi.edu/oah/",
//            tra("Planetary Science Institute"),
//            tra("Astronomy"),
//            tra("Monitor and study the hazard posed by near-Earth asteroids"),
//            "http://orbit.psi.edu/"
//        ),
//        project(
//            "uFluids@home",
//            "http://www.ufluids.net/",
//            tra("Purdue University"),
//            tra("Physics/Aeronautics"),
//            tra("The uFluids project simulates two-phase fluid behavior in microgravity and microfluidics problems. Our goal is to design better satellite propellant management devices and address two-phase flow in microchannel and MEMS devices."),
//            "ufluids.gif"
//        ),
//        project(
//            "Albert@home",
//            "http://albert.phys.uwm.edu/",
//            tra("Univ. of Wisconsin - Milwaukee, Max Planck Institute"),
//            tra("Astrophysics"),
//            "Test project for Einstein@home",
//            ""
//        ),
//        project(
//            "vLHCathome",
//            "http://lhcathome2.cern.ch/vLHCathome/",
//            tra("CERN (European Organization for Nuclear Research)"),
//            tra("Physics"),
//            tra("This project uses CERN-developed virtual machine technology for LHC event physics simulation on volunteer computers.  Requires that you install VirtualBox on your computer"),
//            "t4t.png",
//            "",
//            tra("Simulate high-energy particle collisions")
//        ),
//        project(
//            "ATLAS@Home",
//            "http://atlasathome.cern.ch/",
//            tra("CERN (European Organization for Nuclear Research)"),
//            tra("Physics"),
//            tra("ATLAS@Home uses volunteer computing to run simulations for ATLAS, a particle physics experiment at CERN's Large Hadron Collider.  ATLAS searches for new particles and processes using head-on collisions of protons of extraordinary high energy."),
//            "atlas_at_home.jpg",
//            "",
//            tra("Simulate high-energy particle collisions for CERN")
//        ),
//        project(
//            "Quantum Monte Carlo at Home",
//            "http://qah.uni-muenster.de/",
//            tra("University of Muenster (Germany)"),
//            tra("Chemistry"),
//            tra("Study the structure and reactivity of molecules using Quantum Chemistry."),
//            "logo_oben.jpg"
//        ),
//        project(
//            "Spinhenge@home",
//            "http://spin.fh-bielefeld.de/",
//            tra("Bielefeld University of Applied Sciences"),
//            tra("Chemical engineering and nanotechnology"),
//            tra("The study of molecular magnets and controlled nanoscale magnetism.  These magnetic molecules may be used to develop tiny magnetic switches, with applications in medicine (such as local tumor chemotherapy) and biotechnology."),
//            "rotating-fe30-h90px.gif",
//            "",
//            "Study nanoscale magnetism"
//        ),
//        project(
//            "EDGeS@Home",
//            "http://home.edges-grid.eu/home/",
//            tra("MTA-SZTAKI Laboratory of Parallel and Distributed Systems (Hungary)"),
//            tra("European research projects"),
//            tra("The EDGeS@Home Beta project integrates volunteer computing into the service grid network of Europe by allowing service grids to send workunits to be processed by the volunteers of this project. The scientific projects covered by the project include math, physics, biology, etc."),
//            "logo_edges.png",
//            "",
//            tra("Help European researchers")
//        ),
//        project(
//            "Ibercivis",
//            "http://registro.ibercivis.es/",
//            tra("Spanish universities and research centers"),
//            tra("Various Spanish research projects"),
//            tra("Research in physics, material science, and biomedicine"),
//            "cabecera2.jpg",
//            "",
//            tra("Help Spanish researchers")
//        ),
//        project(
//            "SubsetSum@Home",
//            "http://volunteer.cs.und.edu/subset_sum/",
//            "University of North Dakota, Computer Science Department",
//            tra("Computer Science"),
//            "Research in computational complexity",
//            "",
//            "",
//            "Study the Subset Sum problem"
//        ),
//        project(
//            "OProject@Home",
//            "http://oproject.info/",
//            tra("Independent"),
//            tra("Mathematics, Physics, Artificial Intelligence"),
//            tra("Simulation of quantum computing; Goldbach's conjecture."),
//            "oproject_logo.png",
//            "",
//            "Do research in math, physics, and Artificial Intelligence"
//        ),
//        project(
//            "VolPEx",
//            "http://volpex.cs.uh.edu/VCP/",
//            "University of Houston",
//            "Computer science",
//            "Creating effective parallel computing on multiple volatile nodes. Apply research on REMD Protein Folding.",
//            "",
//            "",
//            "Study parallel computing across multiple computers"
//        ),
//        project(
//            "Mersenne@home",
//            "http://mersenneathome.net/",
//            tra("Independent"),
//            tra("Mathematics"),
//            tra("Mersenne@home searches for 'Mersenne primes' - prime numbers of the form 2<sup>p</sup>-1."),
//
//            "mersenne_logo80.png"
//        ),
//        project(
//            "DistrRTgen",
//            "http://boinc.freerainbowtables.com/distrrtgen/",
//            "Independent",
//            tra("Cryptography"),
//            "To give the world's security experts the best tools available for detecting weak hashes. This can help them to force developers to use more secure methods of password protection.",
//            "freerainbowtables_logo.png",
//            "",
//            "Study hash functions"
//        ),
//        project(
//            "VTU@home",
//            "http://boinc.vgtu.lt/vtuathome/",
//            tra("Vilnius Gediminas Technical University and Kaunas University of Technology (Lithuania)"),
//            tra("Software testing"),
//            tra("The aim of this project is to provide a powerful distributed computing platform for scientists of Vilnius Gediminas Technical University (VGTU) as well as others Lithuanian academic institutions.  Current applications involve the study of Monte-Carlo based software testing."),
//            "vtuathome-white.gif",
//            "",
//            "Help Lithuanian researchers"
//        ),
//        project(
//            "AQUA@home",
//            "http://aqua.dwavesys.com/",
//            tra("D-Wave Systems, Inc."),
//            tra("Quantum computing"),
//            tra("D-Wave's AQUA (Adiabatic QUantum Algorithms) is a research project whose goal is to predict the performance of superconducting adiabatic quantum computers on a variety of hard problems arising in fields ranging from materials science to machine learning. AQUA@home uses Internet-connected computers to help design and analyze quantum computing algorithms, using Quantum Monte Carlo techniques."),
//            "logo_dwave2.png"
//        ),
//        project(
//            "SHA-1 Collision Search Graz",
//            "http://boinc.iaik.tugraz.at/sha1_coll_search/",
//            tra("Graz University of Technology (Austria)"),
//            tra("Cryptography"),
//            tra("Search for collisions (weaknesses) of the widely-used SHA-1 hash function."),
//            "LogoKryptoGroup_klein.jpg"
//        ),
//        project(
//            "ABC@home",
//            "http://abcathome.com/",
//            tra("Mathematical Institute of Leiden University / Kennislink"),
//            tra("Mathematics"),
//            tra("Search for 'abc-triples': positive integers a,b,c such that a+b=c, a &lt; b &lt; c, a,b,c have no common divisors and c > rad(abc), where rad(n) is the product of the distinct prime factors of n. The ABC conjecture says that there are only finitely many a,b,c such that log(c)/log(rad(abc)) > h for any real h > 1. The ABC conjecture is currently one of the greatest open problems in mathematics. If it is proven to be true, a lot of other open problems can be answered directly from it."),
//            "abclogo.jpg",
//            "",
//            "Study the ABC conjecture"
//        ),
//        project(
//            "Riesel Sieve",
//            "http://boinc.rieselsieve.com/",
//            tra("Riesel Sieve community"),
//            tra("Mathematics"),
//            tra("Find prime numbers of the form k*2<sup>n</sup>-1"),
//            ""
//        ),
//        project(
//            "Rectilinear Crossing Number",
//            "http://dist.ist.tugraz.at/cape5/",
//            tra("Graz University of Technology (Austria)"),
//            tra("Mathematics"),
//            tra("What is the least number of crossings a straight-edge drawing of the complete graph on top of a set of n points in the plane obtains?  From very recent (not even published yet) mathematical considerations the rectilinear crossing numbers for n=19 and n=21 are also known. So the most tantalizing problem now is to determine the true value for n=18, which is the main focus of this project."),
//            ""
//        ),
//        project(
//            "Chess960@home",
//            "http://www.chess960athome.org/alpha/",
//            tra("Chess-960.org"),
//            tra("Game study"),
//            tra("This project studies Chess 960, a variant of orthodox chess. In classical chess the starting position of the game never changes.  In Chess 960, just before the start of every game, the initial configuration of the chess pieces is determined randomly."),
//            "chess960athome.jpg"
//        ),
//        project(
//            "NQueens@home",
//            "http://nqueens.ing.udec.cl/",
//            tra("Universidad de Concepción, Chile"),
//            tra("Mathematics"),
//            tra("The eight queens problem consists of trying to place eight queens on a chessboard so that no queen attacks any other queen.  I has long been known that there are 92 solutions, of which 12 are distinct. NQueens@home studies the generalization to N queens on an NxN board, for N=19 and greater."),
//            "NQueens-Logo1b.png"
//        ),
//        project(
//            "sudoku@vtaiwan",
//            "http://sudoku.nctu.edu.tw/",
//            "National Chiao Tung University, Taiwan",
//            tra("Mathematics"),
//            "Sudoku@vtaiwan seeks to solve the minimum Sudoku problem, a well-known problem in mathematics and computer science.",
//            "sudoku.png",
//            "",
//            "Find the minimum Sudoku puzzle"
//        ),
//        project(
//            "Surveill@Home",
//            "http://surveill.dei.uc.pt/surveill",
//            "University of Coimbra, Portugal",
//            "Web performance",
//            tra("Surveill@Home is a research project that conducts end-to-end fine-grained monitoring of web sites.  The project will deploy thousands of probes, each of which repeatedly performs transactions on web sites.  This approach provides end-user failure and performance statistics."),
//            "surveill.png"
//        ),
