<?php

// numeric project and AM IDs.
// NEVER REUSE IDs
//
define('PROJ_QCN',              1);
define('PROJ_RADIOACTIVE',      2);
define('PROJ_MINDMODELING',     3);
define('PROJ_DENIS',            4);
define('PROJ_RNA_WORLD',        5);
define('PROJ_GPU_GRID',         6);
define('PROJ_ROSETTA',          7);
define('PROJ_CPDN',             8);
define('PROJ_ACOUSTICS',        9);
define('PROJ_POGS',            10);
define('PROJ_ASTEROIDS',       11);
define('PROJ_COSMOLOGY',       12);
define('PROJ_UNIVERSE',        13);
define('PROJ_MILKYWAY',        14);
define('PROJ_LEIDEN',          15);
define('PROJ_EINSTEIN',        16);
define('PROJ_LHC',             17);
define('PROJ_SETI',            18);
define('PROJ_CSG',             19);
define('PROJ_CAS',             20);
define('PROJ_YOYO',            21);
define('PROJ_WCG',             22);
define('PROJ_AMICABLE',        23);
define('PROJ_NUMBERFIELDS',    24);
define('PROJ_SAT',             25);
define('PROJ_MOO',             26);
define('PROJ_ENIGMA',          27);
define('PROJ_COLLATZ',         28);
define('PROJ_NFS',             29);
define('PROJ_PRIMEGRID',       30);
define('PROJ_PRIMABOINCA',     31);
define('PROJ_SZTAKI',          32);
define('PROJ_GERASIM',         33);
define('PROJ_SRBASE',          34);
define('PROJ_BAM',             35);
define('PROJ_GRIDREPUBLIC',    36);
define('PROJ_SOURCEFINDER',    37);
define('PROJ_ODLK',            38);
define('PROJ_ODLK1',           39);
define('PROJ_DHEP',            40);
define('PROJ_DBN',              41);
define('PROJ_RAKESEARCH',       42);
define('PROJ_NANOHUB',          43);
define('PROJ_TACC',             44);
define('PROJ_GRCPOOL',         45);
define('PROJ_SCIENCE_UNITED',  101);

?>
